### PR TITLE
encryption psk and agent configuration

### PR DESCRIPTION
**Pull request by stephdl**
Some interrogation about `/etc/zabbix/zabbix_agentd.d/userparameter_nethserver.conf`, do we need it

the goal is to make the setting easily

add the ServerIP

config setprop zabbix-agent ServerIP 1.1.1.1 PskID 001
signal-event netserver-zabbix-agent-update

follow this to enable psk in the UI : https://www.zabbix.com/documentation/4.0/manual/encryption/using_pre_shared_keys

if PskID is set to '', then PSK is not enabled, each agent must have its ID (002,003,004,...)

### CODE REVIEW

**Review by mrmarkuz — CHANGES_REQUESTED** [review]
The PSK encryption is working internal on a VM and public on a VPS. Very nice!
The rabe md raid config isn't working because it's not parsed. I found that /etc/zabbix/zabbix_agentd.conf.d/rabe.md-raid.conf is in a directory that's not included in the config file /etc/zabbix/zabbix_agentd.conf (see line 275) so I propose to move rabe.md-raid.conf to /etc/zabbix/zabbix_agentd.d directory. After using right directory and restarting zabbix-agent, it worked like a charm and the zabbix-server received data about the RAID. Great!

**Comment by stephdl** [comment]
Done, please review, maybe you could update the readme accordingly, do a quick update in your wiki page to explain how to enable encryption with a short howto.

Did you find how to integrate the template by the API, else we can go by a manual way and explain  how to do it.

**Comment by stephdl** [comment]
hum there is something I missed, the psk key will be lost if we do a disaster recovery, we need to include it in the backup or move it to /var/lib/secrets

**Comment by stephdl** [comment]
done, backup should take care of the psk key

**Review by mrmarkuz — APPROVED** [review]
PSK ID, encryption and RAID check are working as expected. Great work!

**Pull request merged**
